config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "top#index"
  resources :scores 
  resources :top, only:[:index]
  resources :rankings, only:[:index]

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  resources :contacts, only: [:new, :create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  validates :content, presence: true
end

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :user 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :scores

  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i
  validates :password, format: { with: VALID_PASSWORD_REGEX }
  validates :nickname, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(_resource)
    scores_path
  end

  def after_sign_out_path_for(_resource)
    root_path
  end

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname])
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.contact_mail(@contact).deliver
      redirect_to scores_path
    else
      render :new
    end
  end

  private

    def contact_params
      params.require(:contact).permit(:name, :content, :email)
    end

end

app/controllers/rankings_controller.rb
class RankingsController < ApplicationController

  def index
    @scores = Score.all.includes(:user).order('score DESC').limit(30)
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :authenticate_user!

  def index
    @score = Score.new
    @scores = current_user.scores.order('created_at DESC')
    @chart = current_user.scores.pluck(:created_at, :score)
  end

  def create
    @score = Score.new(scores_params)
    if @score.save
      redirect_to scores_path
    else

      render :index
    end
  end

  def destroy
    if params[:all].present?
      @score = Score.where(params[:id])
      current_user.scores.destroy_all
    else
      @score = Score.find(params[:id])
      @score.destroy
    end
    redirect_to scores_path
  end

  private

  def scores_params
    params.require(:score).permit(:score).merge(user_id: current_user.id)
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/rankings_helper.rb
module RankingsHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/contacts/new.html.erb
<%= form_with(model: @contact, local: true) do |f| %>
    <div class='form-wrap'>
      <div class='form-header'>
        <h3 class='form-header-text'>
          お問い合わせフォーム
        </h3>
      </div>
    </div>
    <div class="correct-msg-box">
      <% if @contact.errors.any? %>
        <div id="error_explanation">
          <ul><% @contact.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="correct-msg-main">
        <div class="contact-form">

            <div class="correct-text-field">
              <%= f.label "お名前(必須)" %>
              <%= f.text_field :name, placeholder: "お名前", class: "input-form" %>
            </div>

            <div class="correct-text-field">
              <%= f.label "メールアドレス(必須)" %>
              <%= f.email_field :email, class:"input-default", id:"email", placeholder:"PC・携帯どちらでも可", class: "input-form" %>
            </div>

            <div class="correct-text-field">
              <%= f.label "お問合せ内容(必須)" %>
              <%= f.text_area :content, placeholder: "お問合せ内容を入力してください", class: "input-form-correct" %>
            </div>

            <div class="send-btn-contents">
              <div class="register-btn">
                <%= f.button type: "submit", class:"register-red-btn", style:'border-style: none;' do %> 
                  送信 <i class="fas fa-paper-plane"></i>
                <% end %>
              </div>
              <div class="register-btn">
                <%= link_to "戻る", scores_path, class:"register-red-btn", style:"background-color: #aaa" %>
              </div>
            </div>

        </div>
      </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScoreApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
  
    <h1>
        <a href="/">ShootingScore</a>
    </h1>
    
    <% if user_signed_in? %>
        <div class="user_nav ">
          <div class="user_name">
            <%= current_user.nickname %>
          </div>
              <div class="user_out">
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
              </div>
              <div class="contact">
                  <%= link_to "お問い合わせ", new_contact_path( user_id: current_user.id ) %>
              </div>
        <% else %>
          <div class="user_in">
            <%= link_to "ログイン", new_user_session_path, class: "post" %>
          </div>
        </div>
        <% end %>
        
</header>

    <%= yield %>

<footer>
      <p class="footer_a">
        ShootingScore 2021.
      </p>
    </footer>

  </body>
</html>

app/views/rankings/index.html.erb
<div class="ranker">

  <div class="synthesis">
    <u><h2>スコア上位</h2></u>
  </div>

  <div class="score_r">
    <%= render @scores%>

  </div>

</div>

app/views/scores/_score.html.erb
<div class="score_d">

  <div class="score_total">
    <i><p>TOTAL</p></i>
  </div>

  <div class="score_c">
    <b><p><%= score.score %></p></b>
  </div>

<div class="user_name">
  <%= score.user.nickname %>
  </div>

  <div class="score_date">
    <%= l score.created_at %>
  </div>

  
</div>

app/views/scores/index.html.erb
<%= form_with model: @score, class: 'form', local: true do |f| %>
<%= render 'shared/error_messages', model: f.object %>
  <div class="form-input">
    <%= f.number_field :score, step: "0.1", in: 400..650, class: 'form-score', placeholder: 'type a score' %>
  <%= f.submit '送信', class: 'form-submit' %>
  <%= link_to "スコア上位勢", rankings_path, class: "ranking_all" %>
  </div>
<% end %>
<%= javascript_include_tag "//www.google.com/jsapi" %>
<%= line_chart @chart, points: false, series: false, curve: false, discrete: true, xtitle: "日付", ytitle: "スコア", width: "100%", height: "500px", decimal: ",", min: 400, max: 650 %>

<% unless @scores.blank?%>
<div class="score_destroy">
<div class="score_destroy_solo">
  <%= link_to "一番新しいスコアを削除", score_path(@scores.ids, @scores.ids), method: :delete %>
  </div>
  <div class="score_destroy_all">
  <%= link_to "全てのスコアを削除", score_path(@scores.ids, all: true), method: :delete %>
  </div>
</div>
<% end %>

<div id="score_b">
    <%= render @scores%>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/top/index.html.erb
<div class="example">
  <%= image_tag "gpr1.jpeg", size: '1920x1080', class:"pict" %>
  <p>
  あなたの射撃を管理します<br>
  <%= link_to "ログイン", new_user_session_path, class: "post_top" %>
  <%= link_to "新規登録", new_user_registration_path, class: "post_top" %>
  </p>

</div>